CREATE TABLE Corretor (
CodCorretor INT NOT NULL,
NomeCorretor VARCHAR(40),
CONSTRAINT PK_cor PRIMARY KEY(CodCorretor)
);

CREATE TABLE Pessoa 
(
CIC INT NOT NULL,
NomePess VARCHAR(40),
Sexo CHAR(1),
DataNasc DATE,
ConjugeCIC INT,
CONSTRAINT PK_PES PRIMARY KEY(CIC)
);

CREATE TABLE Imovel 
(
CodImovel INT,
DescricaoImovel VARCHAR(40),
PrecoImovel NUMERIC,
AnoImovel CHAR(4),
CONSTRAINT PK_IMO PRIMARY KEY(CodImovel)
);

CREATE TABLE Venda
(CodImovel INT NOT NULL,
CIC INT NOT NULL,
DataVenda DATE,
CodCorretor INT,
CONSTRAINT PK_VEND PRIMARY KEY(codimovel, cic),
CONSTRAINT FK_IMOV FOREIGN KEY(CodImovel) REFERENCES Imovel(codimovel),
CONSTRAINT FK_CICP FOREIGN KEY(CIC) REFERENCES Pessoa (CIC),
CONSTRAINT FK_CORR FOREIGN KEY(CodCorretor) REFERENCES Corretor (codCorretor)
);

ALTER TABLE PESSOA ADD CONSTRAINT FK_PES FOREIGN KEY(ConjugeCIC) REFERENCES Pessoa(CIC)
